name: Build and release packages

permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-zap:
    name: Build ZAP
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-11]
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Initialize...
        run: |
          npm ci

      - name: Verify zap-cli exists in macOS x64 .zip package
        if: startsWith(matrix.os, 'macos')
        uses: GuillaumeFalourd/assert-command-line-output@v2.1
        with:
          command_line: ./node_modules/7zip-bin/mac/x64/7za l ./dist/zap-mac-x64.zip | grep zap-cli
          contains: 'zap-cli'
          expected_result: PASSED

      - name: fileA
        if: startsWith(matrix.os, 'macos')
        uses: GuillaumeFalourd/assert-command-line-output@v2.1
        with:
          command_line: ./node_modules/7zip-bin/mac/x64/7za l ./dist/zap-mac-x64.zip | grep fileA
          contains: fileA

      - name: fileB
        if: startsWith(matrix.os, 'macos')
        uses: GuillaumeFalourd/assert-command-line-output@v2.1
        with:
          command_line: ./node_modules/7zip-bin/mac/x64/7za l ./dist/zap-mac-x64.zip
          contains: fileB

      - name: output
        shell: bash
        run: cat ./output.txt



